import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {LanguageProvider} from "@/contexts/LanguageContext";
import {Footer, Navbar} from "@/components/PageLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  //title: "Create Next App",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col` }
      >
        <LanguageProvider>
            <Navbar/>
            <main className="flex-1 bg-gray-900">
                {children}
            </main>
            <Footer/>
        </LanguageProvider>
      </body>
    </html>
  );
}
